# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CreateAction.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Options import Ui_Options
import os
import json

class Ui_CreateAction(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Options()
        self.ui.setupUi(self.window)    
        self.window.show() 
        
    def setupUi(self, CreateAction):
        CreateAction.setObjectName("CreateAction")
        CreateAction.resize(400, 632)
        self.centralwidget = QtWidgets.QWidget(CreateAction)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame)
        self.pushButton_19.setGeometry(QtCore.QRect(190, 50, 88, 32))
        self.pushButton_19.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_19.setMaximumSize(QtCore.QSize(88, 32))
        font = QtGui.QFont()
        font.setFamily("Work Sans Light")
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("QPushButton:checked {\n"
"background-color: rgb(238, 255, 1);\n"
"color: black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: black;\n"
"  border-radius: 15px;\n"
"  color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  color: rgb(173, 173, 173)\n"
"}")
        self.pushButton_19.setCheckable(True)
        self.pushButton_19.setObjectName("pushButton_19")
        self.buttonGroup = QtWidgets.QButtonGroup(CreateAction)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.pushButton_19)
        self.pushButton_18 = QtWidgets.QPushButton(self.frame)
        self.pushButton_18.setGeometry(QtCore.QRect(100, 50, 88, 32))
        self.pushButton_18.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_18.setMaximumSize(QtCore.QSize(88, 32))
        font = QtGui.QFont()
        font.setFamily("Work Sans Light")
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton:checked {\n"
"background-color: rgb(238, 255, 1);\n"
"color: black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: black;\n"
"  border-radius: 15px;\n"
"  color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  color: rgb(173, 173, 173)\n"
"}")
        self.pushButton_18.setCheckable(True)
        self.pushButton_18.setChecked(True)
        self.pushButton_18.setObjectName("pushButton_18")
        self.buttonGroup.addButton(self.pushButton_18)
        self.pushButton_20 = QtWidgets.QPushButton(self.frame)
        self.pushButton_20.setGeometry(QtCore.QRect(280, 50, 88, 32))
        self.pushButton_20.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_20.setMaximumSize(QtCore.QSize(88, 32))
        font = QtGui.QFont()
        font.setFamily("Work Sans Light")
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("QPushButton:checked {\n"
"background-color: rgb(238, 255, 1);\n"
"color: black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: black;\n"
"  border-radius: 15px;\n"
"  color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  color: rgb(173, 173, 173)\n"
"}")
        self.pushButton_20.setCheckable(True)
        self.pushButton_20.setObjectName("pushButton_20")
        self.buttonGroup.addButton(self.pushButton_20)
        self.pushButton_17 = QtWidgets.QPushButton(self.frame)
        self.pushButton_17.setGeometry(QtCore.QRect(10, 50, 88, 32))
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_17.setMaximumSize(QtCore.QSize(88, 32))
        font = QtGui.QFont()
        font.setFamily("Work Sans Light")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton:checked {\n"
"background-color: rgb(238, 255, 1);\n"
"color: black;\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: black;\n"
"  border-radius: 15px;\n"
"  color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  color: rgb(173, 173, 173)\n"
"}")
        self.pushButton_17.setCheckable(True)
        self.pushButton_17.setAutoRepeat(False)
        self.pushButton_17.setObjectName("pushButton_17")
        self.buttonGroup.addButton(self.pushButton_17)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.frame)
        self.commandLinkButton.setGeometry(QtCore.QRect(270, 0, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setStyleSheet("color: rgb(89, 89, 89);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(146, 93, 221, 255), stop:1 rgba(109, 255, 189, 255));\n"
"border-width: 10px;\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/world.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon)
        self.commandLinkButton.setObjectName("commandLinkButton")

        self.pushButton_25 = QtWidgets.QPushButton(self.frame)
        self.pushButton_25.setGeometry(QtCore.QRect(0, 3, 88, 32))
        self.pushButton_25.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_25.setMaximumSize(QtCore.QSize(88, 32))
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("QPushButton:checked {\n"
"background-color: none;\n"
"color: rgb(89, 89, 89);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: none;\n"
"  border-radius: 15px;\n"
"  color: rgb(89, 89, 89);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  color: rgb(173, 173, 173)\n"
"}")
        self.pushButton_25.setCheckable(True)
        self.pushButton_25.setAutoRepeat(False)
        self.pushButton_25.setObjectName("pushButton_25")

        self.pushButton_21 = QtWidgets.QPushButton(self.frame, clicked = lambda: self.openWindow())
        self.pushButton_21.setGeometry(QtCore.QRect(10, 100, 361, 31))
        self.pushButton_21.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_21.setMaximumSize(QtCore.QSize(16777215, 13516535))
        font = QtGui.QFont()
        font.setFamily("Work Sans Light")
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: black;\n"
"  border: none;\n"
"  border-radius: 15px;\n"
"  color: white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color:nocolor;\n"
"  color: rgb(173, 173, 173)\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: rgb(238, 255, 1);\n"
"  color: black;\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 160, 41, 20))
        self.label.setStyleSheet("font: 8pt \"Work Sans Medium\";")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(20, 190, 51, 51))
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #f2f2f2;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 190, 51, 51))
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #f2f2f2;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 190, 51, 51))
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_3.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #f2f2f2;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(140, 190, 51, 51))
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_4.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #f2f2f2;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(260, 190, 51, 51))
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_5.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #f2f2f2;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(80, 250, 51, 51))
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_6.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #f2f2f2;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 250, 51, 51))
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_7.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #f2f2f2;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(140, 250, 51, 51))
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_8.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #f2f2f2;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setGeometry(QtCore.QRect(80, 400, 51, 51))
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_10.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #cc3363;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}\n"
"\n"
"")
        self.pushButton_10.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/volume-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame)
        self.pushButton_11.setGeometry(QtCore.QRect(140, 400, 51, 51))
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_11.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #f2f2f2;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 310, 61, 20))
        self.label_2.setStyleSheet("font: 8pt \"Work Sans Medium\";")
        self.label_2.setObjectName("label_2")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 400, 51, 51))
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_13.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #cc3363;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  padding: 10px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}\n"
"")
        self.pushButton_13.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/low-volume.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon2)
        self.pushButton_13.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame)
        self.pushButton_14.setGeometry(QtCore.QRect(80, 340, 51, 51))
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_14.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #6264A7;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  padding: 10px 12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}\n"
"\n"
"")
        self.pushButton_14.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/mic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_14.setIcon(icon3)
        self.pushButton_14.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame)
        self.pushButton_15.setGeometry(QtCore.QRect(140, 340, 51, 51))
        self.pushButton_15.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_15.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #6264A7;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  padding: 10px 12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}\n"
"")
        self.pushButton_15.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/webcam.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon4)
        self.pushButton_15.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame)
        self.pushButton_16.setGeometry(QtCore.QRect(20, 340, 51, 51))
        self.pushButton_16.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_16.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: rgb(86, 98, 246);\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  padding: 10px 12px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}\n"
"\n"
"")
        self.pushButton_16.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/discord.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_16.setIcon(icon5)
        self.pushButton_16.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 460, 61, 20))
        self.label_3.setStyleSheet("font: 8pt \"Work Sans Medium\";")
        self.label_3.setObjectName("label_3")
        self.pushButton_22 = QtWidgets.QPushButton(self.frame)
        self.pushButton_22.setGeometry(QtCore.QRect(20, 490, 51, 51))
        self.pushButton_22.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_22.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #91ccec;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}\n"
"\n"
"")
        self.pushButton_22.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/crying_emoji.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_22.setIcon(icon6)
        self.pushButton_22.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.frame)
        self.verticalScrollBar.setGeometry(QtCore.QRect(350, 140, 16, 431))
        self.verticalScrollBar.setStyleSheet("/*Vertical Scroll Bar*/\n"
"QScrollBar:vertical {\n"
"    border:none;\n"
"    background-color: lightgrey;\n"
"    width: 0px;\n"
"    margin: 15px 0 8px 0;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"/*Handle Bar Vertical*/\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #3c3c3c;\n"
"    min-height: 150px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background-color: #3c3c3c;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color: #3c3c3c;\n"
"}\n"
"\n"
"/*BTN Top - Scroll Bar*/\n"
"QScrollBar::sub-line:vertical {\n"
"    border:none;\n"
"    background-color: lightgrey;\n"
"    height: 0px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color: lightgrey;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color: lightgrey;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
" \n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.pushButton_23 = QtWidgets.QPushButton(self.frame)
        self.pushButton_23.setGeometry(QtCore.QRect(200, 340, 51, 51))
        self.pushButton_23.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_23.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #f2f2f2;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.frame)
        self.pushButton_24.setGeometry(QtCore.QRect(260, 340, 51, 51))
        self.pushButton_24.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_24.setMaximumSize(QtCore.QSize(51, 51))
        font = QtGui.QFont()
        font.setFamily("Work Sans")
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("\n"
"QPushButton {\n"
"  /* Set the background color and border for the button */\n"
"  background-color: #f2f2f2;\n"
"  border: none;\n"
"  border-radius: 10px;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  /* Change the background color when the button is hovered over */\n"
"  background-color: #e5e5e5;\n"
"  color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  /* Change the background color when the button is pressed */\n"
"  background-color: #3d3d3d;\n"
"  color: white;\n"
"}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        CreateAction.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CreateAction)
        self.statusbar.setObjectName("statusbar")
        CreateAction.setStatusBar(self.statusbar)

        self.retranslateUi(CreateAction)
        QtCore.QMetaObject.connectSlotsByName(CreateAction)

        # Get path of the "Profiles" folder
        profiles_folder_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Profiles")
        
        # Loop through JSON files in "Profiles" folder
        for file_name in os.listdir(profiles_folder_path):
            if file_name.endswith(".json"):
                # Open JSON file
                with open(os.path.join(profiles_folder_path, file_name), 'r') as f:
                    profile_data = json.load(f)
                    
                    # Get icon path from JSON file
                    icon_path = profile_data.get("icon_path", "")
                    
                    # Create QPushButton with icon
                #     pushButton = QtWidgets.QPushButton(self.centralwidget)
                    if icon_path:
                        icon = QtGui.QIcon(icon_path)
                        pushButton.setIcon(icon)
                        pushButton.setIconSize(QtCore.QSize(16, 16))
                        
                    # Add QPushButton to vertical layout
                    #self.verticalLayout.addWidget(pushButton)

    def retranslateUi(self, CreateAction):
        _translate = QtCore.QCoreApplication.translate
        CreateAction.setWindowTitle(_translate("CreateAction", "SecondWindow"))
        CreateAction.setGeometry(QtCore.QRect(823, 50, 400, 623))
        CreateAction.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        CreateAction.setFixedHeight(623)
        CreateAction.setFixedWidth(400)
        self.pushButton_19.setText(_translate("CreateAction", "MIDI"))
        self.pushButton_18.setText(_translate("CreateAction", "Action"))
        self.pushButton_20.setText(_translate("CreateAction", "Lighting"))
        self.pushButton_17.setText(_translate("CreateAction", "Basic"))
        self.pushButton_25.setText(_translate("CreateAction", "←  Back"))
        self.pushButton_25.clicked.connect(CreateAction.close)
        self.commandLinkButton.setText(_translate("CreateAction", "Community "))
        self.pushButton_21.setText(_translate("CreateAction", "+ Create new action"))
        self.label.setText(_translate("CreateAction", "Design"))
        self.pushButton.setText(_translate("CreateAction", ""))
        self.pushButton_2.setText(_translate("CreateAction", "Logo2"))
        self.pushButton_3.setText(_translate("CreateAction", "Act1"))
        self.pushButton_4.setText(_translate("CreateAction", "Rev"))
        self.pushButton_5.setText(_translate("CreateAction", "Act2"))
        self.pushButton_6.setText(_translate("CreateAction", "Exp"))
        self.pushButton_7.setText(_translate("CreateAction", "Save"))
        self.pushButton_8.setText(_translate("CreateAction", "Png"))
        self.pushButton_11.setText(_translate("CreateAction", "End"))
        self.label_2.setText(_translate("CreateAction", "Streaming"))
        self.label_3.setText(_translate("CreateAction", "Reaction"))
        self.pushButton_23.setText(_translate("CreateAction", "Light 1"))
        self.pushButton_24.setText(_translate("CreateAction", "Light 2"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CreateAction = QtWidgets.QMainWindow()
    ui = Ui_CreateAction()
    ui.setupUi(CreateAction)
    CreateAction.show()
    sys.exit(app.exec_())
