from PyQt5 import QtCore, QtGui, QtWidgets
from NoMadbigConnected import Ui_NoMad
from CreateAction import Ui_CreateAction

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_NoMad()
        self.ui.setupUi(self)
        self.ui.pushButton.clicked.connect(self.openChildWindow)

        # self.ui.pushButton_2.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_14.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_16.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_17.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_18.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_37.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_45.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_3.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_13.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_35.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_44.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_5.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_19.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_34.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_43.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_4.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_26.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_29.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_38.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_8.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_21.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_27.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_36.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_6.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_24.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_31.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_40.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_7.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_22.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_32.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_41.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_67.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_20.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_30.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_39.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_11.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_25.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_33.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_42.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_10.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_23.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_28.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_49.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_12.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_54.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_57.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_59.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_50.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_53.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_56.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_48.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_52.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_51.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_55.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_58.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_60.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_61.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_66.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_65.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_64.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_62.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_63.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_47.clicked.connect(self.openChildWindow)
        # self.ui.pushButton_46.clicked.connect(self.openChildWindow)


    def openChildWindow(self):
        self.child_window = ChildWindow(parent=self)
        self.child_window.show()

class ChildWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.ui = Ui_CreateAction()
        self.ui.setupUi(self)

import sys
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())